{% set name = "crocoddyl" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loco-3d/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 854c65e57fdb6b410cb14ca3dc70f76ec568344144c1d690b413b497abf5ae02

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pinocchio                              # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - pinocchio
    - libboost-python-devel
    - python
    - example-robot-data
    - numpy
  run:
    - eigen
    - eigenpy
    - pinocchio
    - python
    - example-robot-data
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - crocoddyl

about:
  home: http://github.com/loco-3d/crocoddyl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Crocoddyl is an optimal control library for robot control under contact sequence. Its solver is based on various efficient Differential Dynamic Programming (DDP)-like algorithms.
  dev_url: https://github.com/loco-3d/crocoddyl

extra:
  recipe-maintainers:
    - olivier-roussel
    - jorisv
    - jcarpent
