{% set name = "crocoddyl" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loco-3d/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9888df84d7ba29fa3c70feb7141c44c5e807b6b39d70d2a02670d4d1d8ea1655

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - eigen
    - eigenpy
    - pinocchio
    - boost
    - python
    - example-robot-data
  run:
    - eigen
    - eigenpy
    - pinocchio
    - boost
    - python
    - example-robot-data
test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - crocoddyl

about:
  home: http://github.com/loco-3d/crocoddyl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Crocoddyl is an optimal control library for robot control under contact sequence. Its solver is based on various efficient Differential Dynamic Programming (DDP)-like algorithms.
  dev_url: https://github.com/loco-3d/crocoddyl

extra:
  recipe-maintainers:
    - jcarpent
